# Generated by CodiumAI

import pytest
"""
Code Analysis

Main functionalities:
The ZMQCredentials class is a subclass of the Credentials class and is used to represent ZeroMQ credentials. It provides methods to get the identifier and credentials of the ZMQCredentials object.

Methods:
- get_identifier(): returns the identity of the ZMQCredentials object.
- get_credentials(): returns a dictionary containing the public key and secret key of the ZMQCredentials object.
- create(): a static method that creates a new instance of the ZMQCredentials class.

Fields:
- identity: a string representing the identity of the ZMQCredentials object.
- publickey: a string representing the public key of the ZMQCredentials object.
- secretkey: a string representing the secret key of the ZMQCredentials object.
"""


class TestZMQCredentials:

    # Tests that an instance of ZMQCredentials is created with valid identity, publickey, and secretkey values.
    def test_create_valid_instance(self):
        credentials = ZMQCredentials(identity="test_identity",
                                     publickey="test_publickey",
                                     secretkey="test_secretkey")
        assert credentials.identity == "test_identity"
        assert credentials.publickey == "test_publickey"
        assert credentials.secretkey == "test_secretkey"

    # Tests that the get_identifier() method returns the correct identity value.
    def test_get_identifier(self):
        credentials = ZMQCredentials(identity="test_identity",
                                     publickey="test_publickey",
                                     secretkey="test_secretkey")
        assert credentials.get_identifier() == "test_identity"

    # Tests that the create() method raises an exception if the provided identifier is empty or None.
    def test_create_invalid_identifier(self):
        with pytest.raises(Exception):
            ZMQCredentials.create(identifier="",
                                  publickey="test_publickey",
                                  secretkey="test_secretkey")
        with pytest.raises(Exception):
            ZMQCredentials.create(identifier=None,
                                  publickey="test_publickey",
                                  secretkey="test_secretkey")

    # Tests that the create() method raises an exception if the provided kwargs are invalid.
    def test_create_invalid_kwargs(self):
        with pytest.raises(Exception):
            ZMQCredentials.create(identity="test_identity", invalid_kwarg="invalid_value")

    # Tests that the get_credentials() method returns a dictionary with the correct publickey and secretkey values.
    def test_get_credentials(self):
        credentials = ZMQCredentials(identity="test_identity",
                                     publickey="test_publickey",
                                     secretkey="test_secretkey")
        assert credentials.get_credentials() == {
            "publickey": "test_publickey",
            "secretkey": "test_secretkey"
        }

    # Tests that the get_identifier() and get_credentials() methods return None or empty values if the instance of ZMQCredentials has empty or None values for identity, publickey, or secretkey.
    def test_get_methods_empty_values(self):
        credentials = ZMQCredentials(identity="", publickey=None, secretkey="")
        assert credentials.get_identifier() is None
        assert credentials.get_credentials() == {"publickey": None, "secretkey": ""}